version: "3.7"

services:
  back:
    container_name: back
    restart: always
    build: ./back
    volumes:
      - "./back/src:/back/src"
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - mongo

  front:
    container_name: front
    restart: always
    build: ./front
    volumes:
      - "./front/src:/front/src"
    ports:
      - "5173:5173"
    depends_on:
      - back

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
